namespace: coolstore-cicd

resources:
- ../../../tekton/tasks/base
- ../../../tekton/pipelines/common/base
- ../../../tekton/pipelines/catalog/base
- ../../../tekton/pipelines/gateway/base
- ../../../tekton/pipelines/inventory/base
