namespace: coolstore-cicd

generatorOptions:
 disableNameSuffixHash: true

configMapGenerator:
- name: maven-settings
  files:
  - secrets/settings.xml

resources:
- ../../../tekton/tasks/base
- ../../../tekton/pipelines/common/base
- ../../../tekton/pipelines/catalog/base
- ../../../tekton/pipelines/gateway/base
- ../../../tekton/pipelines/inventory/base
