apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: coolstore-cicd

generatorOptions:
 disableNameSuffixHash: true

secretGenerator:
- name: maven-settings
  files:
  - secrets/settings.xml

resources:
- coolstore-devs-rolebinding.yaml
- ../../../tekton/tasks/base
- ../../../tekton/pipelines/common/base
- ../../../tekton/pipelines/catalog/base
- ../../../tekton/pipelines/gateway/base
- ../../../tekton/pipelines/inventory/base
- ../../../tekton/pipelines/web/base
- ../../../tekton/pipelines/create-pull-request/base
