apiVersion: operator.tekton.dev/v1alpha1
kind: TektonChain
metadata:
  name: chain
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  targetNamespace: openshift-pipelines
  artifacts.taskrun.format: in-toto
  artifacts.taskrun.storage: oci
  artifacts.taskrun.signer: x509
  artifacts.oci.storage: oci
  artifacts.oci.format: simplesigning
  artifacts.oci.signer: x509
  transparency.enabled: true