apiVersion: v1
kind: ConfigMap
metadata:
  name: roxsecret-namespaces
  namespace: stackrox
data:
  NAMESPACES: coolstore-cicd
  CENTRAL_URL: central-stackrox.apps.summit23soul.197v.p1.openshiftapps.com