resources:
- git-update-deployment.yaml
- argocd-sync-and-wait-task.yaml
- rox-image-check-task.yaml
- rox-image-scan-task.yaml
- task-create-pr.yaml
- task-image-tag-to-digest.yaml
- task-variables.yaml
- https://github.com/redhat-cop/gitops-catalog/openshift-pipelines-tasks/newman/base
- task-npm.yaml
- task-npm-quality.yaml
