apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: task-create-pr
spec:
  workspaces:
  - name: source
  params:
  - name: title
    type: string
    description: PR Title
  - name: body
    type: string
    default: ""
    description: The body of the PR request
  - name: branch
    type: string
  - name: gitea_server
    type: string
  - name: repo
    type: string
  - name: repo_owner
    type: string
  - name: git_secret
    type: string
    default: gitea
    description: "The name of the secret that has your gitea username and token"
  steps:
    - name: run-commands
      image: registry.access.redhat.com/ubi8-minimal:8.8
      script: |
        #!/usr/bin/env bash

        export data='{"assignee":"$USERNAME","base":"rhdp","head":"$(params.branch)",title":"$(params.title)","body":"$(params.body)"}'

        curl -d $data -H "Content-Type: application/json" -X POST https://$(params.gitea_server)/api/v1/repos/$(params.repo_owner)/$(params.repo)/pulls

      workingDir: $(workspaces.source.path)/git-update-digest-workdir
      env:
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: $(params.git_secret)
              key: password
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: $(params.git_secret)
              key: username
        - name: EMAIL
          valueFrom:
            secretKeyRef:
              name: $(params.git_secret)
              key: email