namespace: coolstore-dev

resources:
- ../../base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:e3088eb468cd6e4bb9efa5b6b5adedf0bac45f25722026356740cb5cb1ada350
  name: quay.io/coolstore-demo/catalog-spring-boot
- digest: sha256:669aed91bd6db38bce558da3c87cd30067c42589e0cdd8ef2e0d978db0479a83
  name: quay.io/coolstore-demo/inventory-quarkus
