namespace: coolstore-dev

resources:
- ../../base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:b92280184a30c3e5e50f76eab943bb22abf0ac7014efa5d052294f9ab2d3fb04
  name: quay.io/coolstore-demo/catalog-spring-boot
