namespace: coolstore-dev

resources:
- ../../base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:14f0e579bcf9bca06bf26878337e9286a403f0da4d398068ba981c62dd984cdc
  name: quay.io/coolstore-demo/catalog-spring-boot
