namespace: coolstore-dev

resources:
- coolstore-devs-rolebinding.yaml
- ../../base

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:e3088eb468cd6e4bb9efa5b6b5adedf0bac45f25722026356740cb5cb1ada350
  name: quay.io/coolstore-demo/catalog-spring-boot
- digest: sha256:43d19b2122328854e8920838b177f68dd5c86843b417127ce0a319459432cafd
  name: quay.io/coolstore-demo/inventory-quarkus
- digest: sha256:1cbab91fa7c5ff48ad8bd1cd919abff51e71c9451265a3c9c8b360aaeb5d5472
  name: quay.io/coolstore-demo/web-nodejs

patches:
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/0
      value:
        name: SECURE_COOLSTORE_GW_ENDPOINT
        value: https://gateway-vertx-coolstore-dev.apps.summit23soul.197v.p1.openshiftapps.com/
  target:
    kind: Deployment
    labelSelector: app=web-nodejs
