apiVersion: v1
kind: Secret
metadata:
  name: git-credentials
  namespace: devspaces
  annotations:
    controller.devfile.io/mount-path: /tmp/.git-credentials/
  labels:
    controller.devfile.io/git-credential: "true"
    controller.devfile.io/watch-secret: "true"
type: Opaque
stringData:
  credentials: http://user1:openshift@https://gitea-gitea.${SUB_DOMAIN}