apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: quay

resources:
- namespace.yaml
- operator-group.yaml
- github.com/redhat-cop/gitops-catalog/quay-registry-operator/operator/overlays/stable-3.6

patches:
  - target:
      kind: Subscription
      name: quay-operator
    patch: |-
      - op: replace
        path: /spec/channel
        value: stable-3.8