---
- hosts: localhost
  connection: local
  vars:
    gitea_username: user1
    gitea_url: http://gitea:3000
    #gitea_url: https://gitea-gitea.apps.cluster-bcc29.bcc29.sandbox167.opentlc.com

    webhooks:
      - repo: inventory-quarkus
        host: el-inventory-coolstore-cicd
      - repo: gateway-vertx
        host: el-gateway-coolstore-cicd
      - repo: catalog-spring-boot
        host: el-catalog-coolstore-cicd
      - repo: web-nodejs
        host: el-web-coolstore-cicd
      # - repo: coolstore
      #   url: https://openshift-gitops-server-openshift-gitops.{{ sub_domain }}/api/webhook

  tasks:

    - name: Use username/password
      set_fact:
        authorization: "Basic {{ (gitea_username + ':' + gitea_password) | b64encode }}"

    - name: Create WebHooks in Gitea
      uri:
        url: "{{ gitea_url}}/api/v1/repos/{{ gitea_username }}/{{ item.repo }}/hooks"
        method: POST
        validate_certs: no
        headers:
          authorization: "{{ authorization }}"
        body_format: json
        body:
          active: true
          branch_filter: "*"
          config:
            content_type: "json"
            url: "https://{{ item.host }}.{{ sub_domain }}"
          events:
            - "push"
          type: "gitea"
        status_code: [201, 400]
      with_items: "{{ webhooks }}"
