apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: coolstore-stage

resources:
- coolstore-devs-rolebinding.yaml
- ../../base

patches:
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/0
      value:
        name: SECURE_COOLSTORE_GW_ENDPOINT
        value: https://gateway-vertx-coolstore-stage.${SUB_DOMAIN}
  target:
    kind: Deployment
    labelSelector: app=web-nodejs
