namespace: coolstore-stage

resources:
- ../../base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:8e3323f0d58e7fb4057716a60f010df3e4b9666166711d17e89e79543305bc18
  name: quay.io/coolstore-demo/catalog-spring-boot
