namespace: coolstore-stage

resources:
- ../../base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:e3088eb468cd6e4bb9efa5b6b5adedf0bac45f25722026356740cb5cb1ada350
  name: quay.io/coolstore-demo/catalog-spring-boot
- digest: sha256:f1a29e71bc0e527d219ad05c017fa8b540e4f3ab3601501639b8f7b85ff3ee30
  name: quay.io/coolstore-demo/inventory-quarkus
- digest: sha256:9aad3fdda67a33bace79e119f287e5c1066ef5d9849b28eaaf4c905d059ecb3f
  name: quay.io/coolstore-demo/web-nodejs

patches:
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/0
      value:
        name: SECURE_COOLSTORE_GW_ENDPOINT
        value: https://gateway-vertx-coolstore-stage.apps.rhte.0x74.p1.openshiftapps.com/
  target:
    kind: Deployment
    labelSelector: app=web-nodejs
