namespace: coolstore-stage

resources:
- ../../base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:e3088eb468cd6e4bb9efa5b6b5adedf0bac45f25722026356740cb5cb1ada350
  name: quay.io/coolstore-demo/catalog-spring-boot
- digest: sha256:7db9d21d6e6bea1fae2c89dbfeb3eed0c47968400d3b39c623ab095659060fd0
  name: quay.io/coolstore-demo/inventory-quarkus
