namespace: coolstore-stage

resources:
- ../../base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:00926a139d58ada79de70777cacef5d3ac200d85b141b8cbff3bd3e6ea052eea
  name: quay.io/coolstore-demo/catalog-spring-boot
