apiVersion: v1
kind: Deployment
metadata:
  name: catalog-spring-boot
spec:
  template:
    spec:
      containers:
        - name: catalog-spring-boot
          image: quay.io/coolstore-demo/catalog-spring-boot:prod        
