namespace: coolstore-prod

resources:
- ../../base
- post-sync-pipeline-job.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:59d51334bc5be3fb8ed37a0e6069e10e2de505152fcb663557553de5ae76e1fe
  name: quay.io/coolstore-demo/inventory-quarkus
- digest: sha256:63df70239b1db895bdbb497309068446256504f52d60f361c8fb4d3f872fb470
  name: quay.io/coolstore-demo/web-nodejs
