namespace: coolstore-prod

resources:
- ../../base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:e3006b6ce973b73630daa05767875260049b6cde3a6561ccde348208d887b97e
  name: quay.io/coolstore-demo/inventory-quarkus
