namespace: coolstore-prod

resources:
- ../../base

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:02a9da75c5702deb8243b7ae6f4323b4beeddc3de34b34ce1ffb97d41c56726d
  name: quay.io/coolstore-demo/inventory-quarkus
- digest: sha256:63df70239b1db895bdbb497309068446256504f52d60f361c8fb4d3f872fb470
  name: quay.io/coolstore-demo/web-nodejs
