namespace: coolstore-prod

resources:
- ../../base
- post-sync-pipeline-job.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:59d51334bc5be3fb8ed37a0e6069e10e2de505152fcb663557553de5ae76e1fe
  name: quay.io/coolstore-demo/inventory-quarkus
- digest: sha256:fc4776cc06dd91e3541b65c2b1e8f76f3b00839b8499ab04a872fc9ba0fb1e6e
  name: quay.io/coolstore-demo/web-nodejs
