namespace: coolstore-prod

resources:
- ../../base
- post-sync-pipeline-job.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:61814d4e43031f5440502b29435829897f4daf5a977bb751f834de5f589edc1a
  name: quay.io/coolstore-demo/inventory-quarkus
- digest: sha256:fc4776cc06dd91e3541b65c2b1e8f76f3b00839b8499ab04a872fc9ba0fb1e6e
  name: quay.io/coolstore-demo/web-nodejs
