---
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: inventory-prod-test
spec:
  serviceAccountName: pipeline
  triggers:
    - name: inventory-prod-test
      template:
        ref: inventory-prod-test