generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: newman-env
    files:
      - config/newman-dev-env.json
      - config/newman-stage-env.json
      - config/newman-prod-env.json

resources:
- inventory-pvc.yaml
- inventory-pipeline.yaml
- inventory-triggertemplate.yaml
- inventory-eventlistener.yaml
- inventory-el-route.yaml
