commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

resources:
  - github.com/redhat-cop/gitops-catalog/advanced-cluster-security-operator/operator/overlays/latest
  - github.com/redhat-cop/gitops-catalog/advanced-cluster-security-operator/instance/overlays/internal-registry-integration
  - init-acs.yaml

patches:
  - patch: |-
      - op: replace
        path: /spec/channel
        value: 'stable'
    target:
      kind: Subscription
      name: rhacs-operator