commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

resources:
  - github.com/redhat-cop/gitops-catalog/advanced-cluster-security-operator/operator/overlays/latest
  - github.com/redhat-cop/gitops-catalog/advanced-cluster-security-operator/instance/overlays/internal-registry-integration
  - init-acs.yaml

patchesJson6902:
  - path: patch-resources.yaml
    target:
      group: platform.stackrox.io
      kind: Central
      name: central
      version: v1alpha1